# Generated by Django 6.0.6 on 2026-07-03 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hu', models.CharField(max_length=10, unique=True)),
                ('descripcion_hu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('ABIERTO', '1. Abierto'), ('ANALISIS', '2. En Análisis'), ('CORRECCION', '3. En Corrección'), ('RESUELTO', '4. Resuelto'), ('CERRADO', '5. Cerrado')], default='ABIERTO', max_length=15)),
                ('historia_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.historiausuario')),
            ],
        ),
    ]
