# Generated by Django 6.0.6 on 2026-07-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('lider', models.CharField(max_length=100)),
                ('integrantes', models.TextField(help_text='Nombres separados por comas')),
            ],
        ),
    ]
