# Generated by Django 6.0.6 on 2026-07-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='defecto',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanban.equipo'),
        ),
    ]
